# Generated by Django 5.2 on 2025-05-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
