# Generated by Django 5.2 on 2025-05-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0002_delete_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='Art.artwork')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Artwork',
                'verbose_name_plural': 'Shared Artworks',
                'ordering': ['-shared_at'],
            },
        ),
    ]
