# Generated by Django 5.2 on 2025-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0003_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
