# Generated by Django 5.2 on 2025-05-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0005_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_featured',
        ),
    ]
